repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        types: [ python ]
      - id: ruff-format
        types: [ python ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        exclude: ^tests/
        additional_dependencies: [ types-toml==0.10.8 ]
        types: [ python ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [ python ]
        args: 
          [
            "-rn",
            "--rcfile=pylintrc",
          ]