repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: [ check --fix ]
        types: [ python ]
      - id: ruff-format
        files: \.py$
        types: [ python ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports ]
        types: [ python ]