[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "artipy"
version = "0.1.0"
description = ""
authors = ["Truman Mulholland <truman.mulholland@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
flake8-bugbear = "^24.2.6"
flake8-pyproject = "^1.2.3"
pytest = "^8.1.1"

[tool.black]
line-length = 88

[tool.flake8]
max-line-length = 88
extend-select = ["B950"]
extend-ignore = ["E203", "E501", "E701"]

[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88