name: CI

on:
  push:
    branches: 
      - main
      - 'feature/**'
    paths: [ 'src/**.py', 'tests/**.py' ]
  pull_request:
    branches: 
      - main
      - 'feature/**'
    paths: [ 'src/**.py', 'tests/**.py' ]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python & Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.12.1
          poetry-version: 1.8.2

      - name: Run Ruff & Pylint
        run: |
          poetry install --only-root
          poetry run ruff check --fix src
          poetry run pylint src
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          poetry install --only-root
          poetry run pytest
  

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black
        run: |
          poetry run black src
    